# Generated by Django 6.0 on 2025-12-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_refillrequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refillrequest',
            table='RefillRequest',
        ),
    ]
