# Generated by Django 6.0 on 2025-12-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_refillrequest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refillrequest',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='refillrequest',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.transaction'),
        ),
    ]
