# Generated by Django 6.0 on 2025-12-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_rename_user_refillrequest_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='TransactionDate',
        ),
    ]
