# Generated by Django 6.0 on 2025-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_externalchargerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refillrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
